//HintName: Bar.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="Bar" />
    /// and creating a new Bar instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class Bar : EveningGreetingArgs
    {

        [SetsRequiredMembers()]
        protected Bar(DataValue<int> ageDataValue, DataValue<string> nameDataValue)
            : base(ageDataValue, nameDataValue)
        {
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
        {
            return new Bar.BarArgsBuilder();
        }

        /// <summary>
        /// </summary>
        internal class BarArgsBuilder : ArgsBuilder<MyArgs>
        {

            public override Command Initialize(Builder<MyArgs> builder)
            {
                var cliDataProvider = GetCliDataProvider(builder);
                var cmd = new System.CommandLine.Command("bar")
                {
                    Description = null,
                };

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 22; });
                return cmd;
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(Builder<MyArgs> builder)
            {
                var validationFailures = new List<ValidationFailure?>();
                return validationFailures
           .Where(x => x is not null)
           .Select(x => x!);
            }

            protected override MyArgs CreateInstance(Builder<MyArgs> builder)
            {
                var ageDataValue = builder.GetDataValue<int>("Age");
                var nameDataValue = builder.GetDataValue<string>("Name");

                var newArgs = new Bar(ageDataValue, nameDataValue);
                return newArgs;
            }
        }
    }
}
