//HintName: MyArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
    /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class MyArgs : IArgs<MyArgs>
    {

        [SetsRequiredMembers()]
        protected MyArgs()
        {
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
        {
            return new MyArgs.MyArgsArgsBuilder();
        }

        /// <summary>
        /// </summary>
        internal class MyArgsArgsBuilder : ArgsBuilder<MyArgs>
        {

            public override Command Initialize(Builder<MyArgs> builder)
            {
                var cliDataProvider = GetCliDataProvider(builder);
                var cmd = new System.CommandLine.RootCommand("my")
                {
                    Description = null,
                };

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return ; });
                return cmd;
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(Builder<MyArgs> builder)
            {
                var validationFailures = new List<ValidationFailure?>();
                return validationFailures
           .Where(x => x is not null)
           .Select(x => x!);
            }

            protected override MyArgs CreateInstance(Builder<MyArgs> builder)
            {

                var newArgs = new MyArgs();
                return newArgs;
            }
        }
    }
}
