//HintName: Cli.cs
// <auto-generated />
# nullable enable

using DragonFruit2;

/// <summary>
/// Auto-generated partial class that supplies the root ArgsBuilder.
/// </summary>
public class Cli
{

    public static Result<MyArgs> ParseArgs<TRootArgs>(string[]? args = null)
          where TRootArgs : IArgs<TRootArgs>
    {
        return DragonFruit2.Cli.ParseArgs<MyArgs>(new MyArgs.MyArgsArgsBuilder(), args);
    }
}
