//HintName: EveningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="EveningGreetingArgs" />
    /// and creating a new EveningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class EveningGreetingArgs : MyArgs
    {


        public EveningGreetingArgs()
        {
        }
        [SetsRequiredMembers()]
        protected EveningGreetingArgs(DataValue<int> ageDataValue, DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
            if (ageDataValue.IsSet) Age = ageDataValue.Value;
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
        {
            return new EveningGreetingArgs.EveningGreetingArgsArgsBuilder();
        }

        /// <summary>
        /// </summary>
        internal class EveningGreetingArgsArgsBuilder : ArgsBuilder<MyArgs>
        {

            public override Command Initialize(Builder<MyArgs> builder)
            {
                var cliDataProvider = GetCliDataProvider(builder);
                var cmd = new System.CommandLine.Command("evening-greeting")
                {
                    Description = null,
                };

                var ageOption = new Option<int>("--age")
                {
                    Description = null,
                    Required = false,
                    Recursive=true
                };
                cliDataProvider.AddNameLookup("Age", ageOption);
                cmd.Add(ageOption);

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 25; });
                return cmd;
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(Builder<MyArgs> builder)
            {
                var validationFailures = new List<ValidationFailure?>();
                return validationFailures
           .Where(x => x is not null)
           .Select(x => x!);
            }

            protected override MyArgs CreateInstance(Builder<MyArgs> builder)
            {
                var ageDataValue = builder.GetDataValue<int>("Age");
                var nameDataValue = builder.GetDataValue<string>("Name");

                var newArgs = new EveningGreetingArgs(ageDataValue, nameDataValue);
                return newArgs;
            }
        }
    }
}
