using DragonFruit2.GeneratorSupport;
using System.Text;
using Xunit;

namespace DragonFruit2.Generators.Test
{
    public class CodeCreationTests
    {

        [Fact]
        public async Task OutputsClassForCommandInfo()
        {
            var commandInfo = new CommandInfo
            {
                Name = "MyCommand",
                NamespaceName = "MyNamespace",
            };

            var expected = """"
                // <auto-generated />
                using DragonFruit2;
                using System.CommandLine;
                using System.Diagnostics.CodeAnalysis;

                namespace MyNamespace
                {
                    /// <summary>
                    /// Auto-generated partial class for building CLI commands for <see cref="MyCommand" />
                    /// and creating a new MyCommand instance from a <see cref="System.CommandLine.ParseResult" />.
                    /// </summary>
                    public partial class MyCommand : IArgs<MyCommand>
                    {
                        public static void Initialize(Builder<MyCommand> builder)
                        {
                            var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyCommand>>().FirstOrDefault();
                            if (cliDataProvider is null)
                            {
                                cliDataProvider = new CliDataProvider<MyCommand>();
                                builder.DataProviders.Add(cliDataProvider);
                            }

                            var rootCommand = new System.CommandLine.Command("MyCommand")
                            {
                                Description = null,
                            };

                            cliDataProvider.RootCommand = rootCommand;
                        }

                        public MyCommand()
                        {
                        }

                        [SetsRequiredMembers()]
                        private MyCommand()
                            : this()
                        {
                        }

                        public static MyCommand Create(Builder<MyCommand> builder)
                        {

                            var newArgs = new MyCommand()
                            return newArgs;
                        }
                    }
                }

                """";

            var actual = DragonFruit2Builder.GetSourceForCommandInfo(commandInfo);

            Assert.Equal(expected, actual);
        }

        [Fact]
        public async Task OutputSetsCommandDescription()
        {
            var commandInfo = new CommandInfo
            {
                Name = "MyCommand",
                NamespaceName = "MyNamespace",
                Description = "This is my command"
            };

            var expectedMarker = "var rootCommand = new System.CommandLine.Command(\"MyCommand\")";
            var expected = $$"""
                {{expectedMarker}}
                            {
                                Description = "This is my command",
                            };
                """;

            var actual = DragonFruit2Builder.GetSourceForCommandInfo(commandInfo);
            var position = actual.IndexOf(expectedMarker);
            var testString = actual[position..(position + expected.Length)]; // Trim to relevant part

            Assert.Equal(expected, testString);
        }

        [Fact]
        public async Task OutputsOptionDeclaration()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OutputsOptionDescription()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
                Description = "This is my option"

            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = "This is my option",
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());

        }

        [Fact]
        public async Task OptionRequiredWhenModifier()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                HasRequiredModifier = true

            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = true
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OptionNotRequiredWhenNonNullableValueType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
                IsValueType = true,
            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OptionRequiredWhenNonNullableReferenceType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                NullableAnnotation = Microsoft.CodeAnalysis.NullableAnnotation.NotAnnotated,
            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = true
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }


        [Fact]
        public async Task OptionNotRequiredWhenNullableReferenceType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                NullableAnnotation = Microsoft.CodeAnalysis.NullableAnnotation.Annotated,
            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }
    }
}
