using DragonFruit2.GeneratorSupport;
using Xunit;

namespace DragonFruit2.Generators.Test;

public class CommandInfoTheoryData : TheoryData<string, string, string, CommandInfo, string>
{
    public CommandInfoTheoryData()
    {
        Add("Empty args class",
            """
            public partial class MyArgs
            { }
            """,
            TestHelpers.EmptyConsoleAppCode,
            new CommandInfo()
            {
                Name = "MyArgs"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;

            public partial class MyArgs : IArgs<MyArgs>
            {
                public static System.CommandLine.Command CreateCli()
                {
                    var rootCommand = new System.CommandLine.Command("Test")
                        {
                            Description = null
                        };
                    return rootCommand;
                }
            
                public static MyArgs Create(ParseResult parseResult)
                {
                    var newArgs = new MyArgs()
                    {
                    };
                    return newArgs;
                }
            }

            """);

        Add("Empty args struct",
            """
            public partial struct MyArgs
            { }
            """,
           TestHelpers.EmptyConsoleAppCode,
           new CommandInfo()
           {
               Name = "MyArgs",
               IsStruct = true,
           },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            
            public partial struct MyArgs : IArgs<MyArgs>
            {
                public static System.CommandLine.Command CreateCli()
                {
                    var rootCommand = new System.CommandLine.Command("Test")
                        {
                            Description = null
                        };
                    return rootCommand;
                }
            
                public static MyArgs Create(ParseResult parseResult)
                {
                    var newArgs = new MyArgs()
                    {
                    };
                    return newArgs;
                }
            }

            """);

        Add("Args w/ namespace (curly)",
            """
            namespace MyNamespace
            {
                public partial class MyArgs
                { }
            }
            """,
            TestHelpers.EmptyConsoleAppCodeWithArgsMyNamespace,
            new CommandInfo()
            {
                Name = "MyArgs",
                NamespaceName = "MyNamespace"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            
            namespace MyNamespace
            {
                public partial class MyArgs : IArgs<MyArgs>
                {
                    public static System.CommandLine.Command CreateCli()
                    {
                        var rootCommand = new System.CommandLine.Command("Test")
                            {
                                Description = null
                            };
                        return rootCommand;
                    }
            
                    public static MyArgs Create(ParseResult parseResult)
                    {
                        var newArgs = new MyArgs()
                        {
                        };
                        return newArgs;
                    }
                }
            }

            """);

        Add("Args w/ namespace (semi-colon)",
            """
            namespace MyNamespace;
            public partial class MyArgs
            { }
            """,
            TestHelpers.EmptyConsoleAppCodeWithArgsMyNamespace,
            new CommandInfo()
            {
                Name = "MyArgs",
                NamespaceName = "MyNamespace"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            
            namespace MyNamespace
            {
                public partial class MyArgs : IArgs<MyArgs>
                {
                    public static System.CommandLine.Command CreateCli()
                    {
                        var rootCommand = new System.CommandLine.Command("Test")
                            {
                                Description = null
                            };
                        return rootCommand;
                    }
            
                    public static MyArgs Create(ParseResult parseResult)
                    {
                        var newArgs = new MyArgs()
                        {
                        };
                        return newArgs;
                    }
                }
            }

            """);


    }

}

