using DragonFruit2.GeneratorSupport;
using Xunit;

namespace DragonFruit2.Generators.Test;

public class CommandInfoTheoryData : TheoryData<string, string, string, CommandInfo, string>
{
    public CommandInfoTheoryData()
    {
        Add("Empty args class",
            """
            public partial class MyArgs
            { }
            """,
            TestHelpers.EmptyConsoleAppCode,
            new CommandInfo()
            {
                Name = "MyArgs"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            using System.Diagnostics.CodeAnalysis;
            
            /// <summary>
            /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
            /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
            /// </summary>
            public partial class MyArgs : IArgs<MyArgs>
            {
                public static void Initialize(Builder<MyArgs> builder)
                {
                    var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
                    if (cliDataProvider is null)
                    {
                        cliDataProvider = new CliDataProvider<MyArgs>();
                        builder.DataProviders.Add(cliDataProvider);
                    }
            
                    var rootCommand = new System.CommandLine.Command("MyArgs")
                    {
                        Description = null,
                    };
            
                    cliDataProvider.RootCommand = rootCommand;
                }
            
                public MyArgs()
                {
                }
            
                [SetsRequiredMembers()]
                private MyArgs()
                    : this()
                {
                }
            
                public static MyArgs Create(Builder<MyArgs> builder)
                {
            
                    var newArgs = new MyArgs()
                    return newArgs;
                }
            }

            """);

        Add("Empty args struct",
            """
            public partial struct MyArgs
            { }
            """,
           TestHelpers.EmptyConsoleAppCode,
           new CommandInfo()
           {
               Name = "MyArgs",
               IsStruct = true,
           },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            using System.Diagnostics.CodeAnalysis;
            
            /// <summary>
            /// Auto-generated partial struct for building CLI commands for <see cref="MyArgs" />
            /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
            /// </summary>
            public partial struct MyArgs : IArgs<MyArgs>
            {
                public static void Initialize(Builder<MyArgs> builder)
                {
                    var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
                    if (cliDataProvider is null)
                    {
                        cliDataProvider = new CliDataProvider<MyArgs>();
                        builder.DataProviders.Add(cliDataProvider);
                    }
            
                    var rootCommand = new System.CommandLine.Command("MyArgs")
                    {
                        Description = null,
                    };
            
                    cliDataProvider.RootCommand = rootCommand;
                }
            
                public MyArgs()
                {
                }
            
                [SetsRequiredMembers()]
                private MyArgs()
                    : this()
                {
                }
            
                public static MyArgs Create(Builder<MyArgs> builder)
                {
            
                    var newArgs = new MyArgs()
                    return newArgs;
                }
            }
            
            """);

        Add("Args w/ namespace (curly)",
            """
            namespace MyNamespace
            {
                public partial class MyArgs
                { }
            }
            """,
            TestHelpers.EmptyConsoleAppCodeWithArgsMyNamespace,
            new CommandInfo()
            {
                Name = "MyArgs",
                NamespaceName = "MyNamespace"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using System.CommandLine;
            using System.Diagnostics.CodeAnalysis;
            
            namespace MyNamespace
            {
                /// <summary>
                /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
                /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
                /// </summary>
                public partial class MyArgs : IArgs<MyArgs>
                {
                    public static void Initialize(Builder<MyArgs> builder)
                    {
                        var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
                        if (cliDataProvider is null)
                        {
                            cliDataProvider = new CliDataProvider<MyArgs>();
                            builder.DataProviders.Add(cliDataProvider);
                        }
            
                        var rootCommand = new System.CommandLine.Command("MyArgs")
                        {
                            Description = null,
                        };
            
                        cliDataProvider.RootCommand = rootCommand;
                    }
            
                    public MyArgs()
                    {
                    }
            
                    [SetsRequiredMembers()]
                    private MyArgs()
                        : this()
                    {
                    }
            
                    public static MyArgs Create(Builder<MyArgs> builder)
                    {
            
                        var newArgs = new MyArgs()
                        return newArgs;
                    }
                }
            }
            
            """);

    }

}

