// <auto-generated />
using DragonFruit2;
using DragonFruit2;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : IArgs<MyArgs>
{
    public static void Initialize(Runner <MyArgs> runner)
    {
        var cliDataProvider = runner.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
        if (cliDataProvider != null)
        {
            cliDataProvider = new CliDataProvider<MyArgs>();
            runner.DataProviders.Add(cliDataProvider);
        }
        cliDataProvider.Command = Build(cliDataProvider);


        System.CommandLine.Command Build(CliDataProvider<MyArgs> dataProvider)
        {
            var rootCommand = new System.CommandLine.Command("Test")
            {
                Description = "This is a test command"
            };
            var nameOption = new Option<string>("--name")
            {
                Description = "Your name",
                Required = true
            };
            dataProvider.AddNameLookup(nameof(Name), nameOption);
            rootCommand.Add(nameOption);

            var ageOption = new Option<System.Int32>("--age")
            {
                Description = "Your Age"
            };
            dataProvider.AddNameLookup(nameof(Age), ageOption);
            rootCommand.Add(ageOption);

            var greetingOption = new Option<System.String>("--greeting")
            {
                Description = "Greeting message"
            };
            dataProvider.AddNameLookup(nameof(Greeting), greetingOption);
            rootCommand.Add(greetingOption);

            rootCommand.Add(new System.CommandLine.Command("TestChild"));
            return rootCommand;
        }
    }

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        if (nameDataValue.IsSet) Name = nameDataValue.Value;
        if (ageDataValue.IsSet) Age = ageDataValue.Value;
        if (greetingDataValue.IsSet) Greeting = greetingDataValue.Value;
    }

    public static MyArgs Create(Runner<MyArgs> runner)
    {
        var nameDataValue = runner.GetDataValue<string>("Name");
        var ageDataValue = runner.GetDataValue<Int32>("Age");
        var greetingDataValue = runner.GetDataValue<string>("Greeting");

        var newArgs = new MyArgs(nameDataValue, ageDataValue, greetingDataValue);
        return newArgs;
    }
}
