// <auto-generated />
using DragonFruit2;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : IArgs<MyArgs>
{
    public static void Initialize(Builder<MyArgs> builder)
    {
        var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
        if (cliDataProvider is null)
        {
            cliDataProvider = new CliDataProvider<MyArgs>();
            builder.DataProviders.Add(cliDataProvider);
        }

        var rootCommand = new System.CommandLine.Command("Test")
        {
            Description = "This is a test command"
        };
        var nameOption = new Option<string>("--name")
        {
            Description = "Your name",
            Required = true
        };
        cliDataProvider.AddNameLookup(nameof(Name), nameOption);
        rootCommand.Add(nameOption);

        var ageOption = new Option<System.Int32>("--age")
        {
            Description = "Your Age"
        };
        cliDataProvider.AddNameLookup(nameof(Age), ageOption);
        rootCommand.Add(ageOption);

        var greetingOption = new Option<System.String>("--greeting")
        {
            Description = "Greeting message"
        };
        cliDataProvider.AddNameLookup(nameof(Greeting), greetingOption);
        rootCommand.Add(greetingOption);

        rootCommand.Add(new System.CommandLine.Command("TestChild"));
        cliDataProvider.RootCommand = rootCommand;
    }

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        if (nameDataValue.IsSet) Name = nameDataValue.Value;
        if (ageDataValue.IsSet) Age = ageDataValue.Value;
        if (greetingDataValue.IsSet) Greeting = greetingDataValue.Value;
    }

    public static MyArgs Create(Builder<MyArgs> builder)
    {
        var nameDataValue = builder.GetDataValue<string>("Name");
        var ageDataValue = builder.GetDataValue<Int32>("Age");
        var greetingDataValue = builder.GetDataValue<string>("Greeting");

        var newArgs = new MyArgs(nameDataValue, ageDataValue, greetingDataValue);
        return newArgs;
    }
}
