// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;
using System.Security.Cryptography;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : IArgs<MyArgs>
{
    private List<Validator<int>>? ageValidators;

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        if (nameDataValue.IsSet) Name = nameDataValue.Value;
        if (ageDataValue.IsSet) Age = ageDataValue.Value;
        if (greetingDataValue.IsSet) Greeting = greetingDataValue.Value;
    }


    public IEnumerable<ValidationFailure> Validate()
    {
        var failures = new List<ValidationFailure>();
        InitializeValidators();

        if (ageValidators is not null)
        {
            foreach (var validator in ageValidators)
            {
                failures.AddRange(validator.Validate(Age));
            }
        }

        return failures;
    }

    /// <summary>
    /// Initializes the collection of age validators with default validation rules.
    /// </summary>
    /// <remarks>
    /// This is a separate method because it will also be called by future code that 
    /// reports valdiation for extended help.
    /// </remarks>
    public void InitializeValidators()
    {
        ageValidators ??= new List<Validator<int>>();
        ageValidators.Add(new GreaterThanValidator<int>("Age", 0));

        // Other properties do not have validation, so their validators remain null.
    }

    static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

    public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
    {
        return new MyArgs.MyArgsBuilder();
    }

    /// <summary>
    /// This static builder supplies the CLI declaration and filling the Result and 
    /// return instance.
    /// </summary>
    /// <remarks>
    /// The first type argument of the base is the Args type this builder creates, and the second is the root Args type. 
    /// This means the two type arguments are the same for the root ArgsBuilder, but will differ for subcommand ArgsBuilders.
    /// </remarks>
    public class MyArgsBuilder : ArgsBuilder<MyArgs>
    {
        static MyArgsBuilder()
        {
            ArgsBuilderCache<MyArgs>.AddArgsBuilder<MyArgs>(new MyArgsBuilder());
        }

        public MyArgsBuilder()
        {

        }

        public override void Initialize(Builder<MyArgs> builder)
        {
            // Generate for each data provider
            InitializeCli(builder, builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault());
            InitializeDefaults(builder, builder.DataProviders.OfType<DefaultDataProvider<MyArgs>>().FirstOrDefault());
        }

        private void InitializeDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs>? defaultDataProvider)
        {
            if (defaultDataProvider is null) return;

            // RegisterDefaults for attribute values and initialization

            RegisterCustomDefaults(builder, defaultDataProvider);
        }


        public override Command InitializeCli(Builder<MyArgs> builder, CliDataProvider<MyArgs>? cliDataProvider)
        {
            if (cliDataProvider is null) throw new ArgumentNullException(nameof(cliDataProvider));

            var rootCommand = new System.CommandLine.Command("Test")
            {
                Description = "This is a test command"
            };
            var nameOption = new Option<string>("--name")
            {
                Description = "Your name",
                Required = true
            };
            cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Name)), nameOption);
            rootCommand.Add(nameOption);

            var ageOption = new Option<System.Int32>("--age")
            {
                Description = "Your Age"
            };
            cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Age)), ageOption);
            rootCommand.Add(ageOption);

            var greetingOption = new Option<System.String>("--greeting")
            {
                Description = "Greeting message"
            };
            cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Greeting)), greetingOption);
            rootCommand.Add(greetingOption);

            rootCommand.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 0; });

            cliDataProvider.RootCommand = rootCommand;

            return rootCommand;
        }

        protected override IEnumerable<ValidationFailure> CheckRequiredValues(Builder<MyArgs> builder)
        {
            var validationFailures = new List<ValidationFailure?>();
            validationFailures.Add(CheckRequiredValue<string>("Name", builder.GetDataValue<string>((typeof(MyArgs), "Name"))));
            return validationFailures
                    .Where(x => x is not null)
                    .Select(x => x!);
        }

        protected override MyArgs CreateInstance(Builder<MyArgs> builder)
        {
            var nameDataValue = builder.GetDataValue<string>( (typeof(MyArgs), "Name"));
            var ageDataValue = builder.GetDataValue<int>((typeof(MyArgs), "Age"));
            var greetingDataValue = builder.GetDataValue<string>((typeof(MyArgs), "Greeting"));

            var newArgs = new MyArgs(nameDataValue, ageDataValue, greetingDataValue);
            return newArgs;
        }
    }



    public class MyArgsDataValues
    {
        internal MyArgsDataValues(Builder<MyArgs> builder)
        {
            this.builder = builder; // Suppress CS8618 by assigning a non-null value (null-forgiving operator)
        }

        private Builder<MyArgs> builder;

        public DataValue<string>? NameDataValue => field ??= builder.GetDataValue<string>((typeof(MyArgs), nameof(NameDataValue)));
        public DataValue<int>? AgeDataValue => field ??= builder.GetDataValue<int>((typeof(MyArgs), nameof(NameDataValue)));
        public DataValue<string>? GreetingDataValue => field ??= builder.GetDataValue<string>((typeof(MyArgs), nameof(NameDataValue)));
    }
}
