// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http.Headers;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : IArgs<MyArgs>
{
    private List<Validator<int>>? ageValidators;

    public IEnumerable<ValidationFailure> ValidationFailures { get; private set; } = [];

    public static void Initialize(Builder<MyArgs> builder)
    {
        var cliDataProvider = builder.DataProviders.OfType<CliDataProvider<MyArgs>>().FirstOrDefault();
        if (cliDataProvider is null)
        {
            cliDataProvider = new CliDataProvider<MyArgs>();
            builder.DataProviders.Add(cliDataProvider);
        }

        var rootCommand = new System.CommandLine.Command("Test")
        {
            Description = "This is a test command"
        };
        var nameOption = new Option<string>("--name")
        {
            Description = "Your name",
            Required = true
        };
        cliDataProvider.AddNameLookup(nameof(Name), nameOption);
        rootCommand.Add(nameOption);

        var ageOption = new Option<System.Int32>("--age")
        {
            Description = "Your Age"
        };
        cliDataProvider.AddNameLookup(nameof(Age), ageOption);
        rootCommand.Add(ageOption);

        var greetingOption = new Option<System.String>("--greeting")
        {
            Description = "Greeting message"
        };
        cliDataProvider.AddNameLookup(nameof(Greeting), greetingOption);
        rootCommand.Add(greetingOption);

        rootCommand.Add(new System.CommandLine.Command("TestChild"));
        cliDataProvider.RootCommand = rootCommand;
    }

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        if (nameDataValue.IsSet) Name = nameDataValue.Value;
        if (ageDataValue.IsSet) Age = ageDataValue.Value;
        if (greetingDataValue.IsSet) Greeting = greetingDataValue.Value;


    }

    public static MyArgs Create(Builder<MyArgs> builder)
    {
        var nameDataValue = builder.GetDataValue<string>("Name");
        var ageDataValue = builder.GetDataValue<Int32>("Age");
        var greetingDataValue = builder.GetDataValue<string>("Greeting");

        var newArgs = new MyArgs(nameDataValue, ageDataValue, greetingDataValue);

        newArgs.ValidationFailures = newArgs.Validate();

        return newArgs;
    }

    public IEnumerable<ValidationFailure> Validate()
    {
        var failures = new List<ValidationFailure>();
        InitializeValidators();

        if (ageValidators is not null)
        {
            foreach (var validator in ageValidators)
            {
                failures.Concat(validator.Validate(Age));
            }
        }

        return failures;
    }

    /// <summary>
    /// Initializes the collection of age validators with default validation rules.
    /// </summary>
    /// <remarks>
    /// This is a separate method because it will also be called by future code that 
    /// reports valdiation for extended help.
    /// </remarks>
    public void InitializeValidators()
    {
        ageValidators ??= new List<Validator<int>>();
        ageValidators.Add(new GreaterThanValidator<int>("Age", 0));

        // Other properties do not have validation, so their validators remain null.
    }
}
