using DragonFruit2.GeneratorSupport;

namespace DragonFruit2.Generators;

// The Cli uses a trick base on C# overload resolution behavior. Items in the current namespace have precedence over those in imported namespaces.
// When the user initially creates the app, importing DragonFruit2 supplies a CLI class for IntelliSense. When generation occurs, this call
// is replaced with the generated CLI. This design allows access to the RootArgsBuilder without complicating user code. In modern .NET, this 
// could also be done with a static interface method. However, old .NET Framework...
public class OutputCli
{
    internal static string GetSource(IEnumerable<CommandInfo> commandInfos)
    {
        var commandInfo = commandInfos
                .Single(c => c.ParentCommandInfo == null);
        var sb = new StringBuilderWrapper();
        FileOpening(sb, commandInfo.CliNamespaceName, commandInfo.NamespaceName);
        sb.OpenNamespace(commandInfo.CliNamespaceName);

        OpenClass(commandInfo, sb);
        ParseArgsMethod(commandInfo, sb)    ;

        sb.CloseClass();
        sb.CloseNamespace(commandInfo.CliNamespaceName);
        return sb.ToString();
    }

    private static void FileOpening(StringBuilderWrapper sb, string? cliNamespace, string? argsNamespace)
    {
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;"]);
        // This is necessary when the RootArgs is not in the same namespace as the call to `Cli.TryParse`, such as top-level statements 
        if (!string.IsNullOrEmpty(argsNamespace) && cliNamespace != argsNamespace)
        {
            sb.AppendLine($"using {argsNamespace};");
        }
    }

    internal static void OpenClass(CommandInfo commandInfo, StringBuilderWrapper sb)
    { 
        sb.AppendLines([
                "/// <summary>",
                $"""/// Auto-generated partial class that supplies the root ArgsBuilder type.""",
                "/// </summary>",
                $"{commandInfo.ArgsAccessibility} class Cli"]);
        sb.OpenCurly();
    }

    private static void ParseArgsMethod(CommandInfo rootCommandInfo, StringBuilderWrapper sb)
    {
        var rootName = rootCommandInfo.Name;
        sb.OpenMethod($"public static Result<{rootName}> ParseArgs<TRootArgs>(string[]? args = null)",
            constraints: "TRootArgs : IArgs<TRootArgs>");
        sb.AppendLine($"return DragonFruit2.Cli.ParseArgs<{rootName}, {rootName}.{rootName}ArgsBuilder>(args);");
        sb.CloseMethod();
    }
}

