using DragonFruit2.GeneratorSupport;

namespace DragonFruit2.Generators;

public class OutputCli
{
    internal static string GetSource(IEnumerable<CommandInfo> commandInfos)
    {
        var commandInfo = commandInfos
                .Single(c => c.ParentCommandInfo == null);
        var sb = new StringBuilderWrapper();
        FileOpening(sb, commandInfo.CliNamespaceName, commandInfo.NamespaceName);
        sb.OpenNamespace(commandInfo.CliNamespaceName);

        OpenClass(commandInfo, sb);
        ParseArgsMethod(commandInfo, sb)    ;

        sb.CloseClass();
        sb.CloseNamespace(commandInfo.CliNamespaceName);
        return sb.ToString();
    }

    private static void FileOpening(StringBuilderWrapper sb, string? cliNamespace, string? argsNamespace)
    {
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;"]);
        if (!string.IsNullOrEmpty(argsNamespace) && cliNamespace != argsNamespace)
        {
            sb.AppendLine($"using {argsNamespace};");
        }
    }

    internal static void OpenClass(CommandInfo commandInfo, StringBuilderWrapper sb)
    { 
        sb.AppendLines([
                "/// <summary>",
                $"""/// Auto-generated partial class that supplies the root ArgsBuilder.""",
                "/// </summary>",
                $"{commandInfo.ArgsAccessibility} class Cli"]);
        sb.OpenCurly();
    }

    private static void ParseArgsMethod(CommandInfo commandInfo, StringBuilderWrapper sb)
    {
        sb.OpenMethod($"public static Result<{commandInfo.Name}> ParseArgs<TRootArgs>(string[]? args = null)",
            constraints: "TRootArgs : IArgs<TRootArgs>");
        sb.AppendLine($"return DragonFruit2.Cli.ParseArgs<{commandInfo.Name}>(new {commandInfo.Name}.{commandInfo.Name}ArgsBuilder(), args);");
        sb.CloseMethod();
    }
}
