using DragonFruit2.GeneratorSupport;

namespace DragonFruit2.Generators;

internal class OutputPartialArgs
{
    internal static void GetSourcePartialArgs(CommandInfo commandInfo, List<(string hintName, string code)> outputStrings)
    {
        var sb = new StringBuilderWrapper();
        FileOpening(sb);
        sb.OpenNamespace(commandInfo.NamespaceName);

        OpenClass(commandInfo, sb);

        FieldsAndProperties(sb, commandInfo);
        sb.AppendLine();
        Constructors(sb, commandInfo);
        ValidateMethod(sb, commandInfo);
        InitializeValidatorsMethod(sb, commandInfo);
        GetArgsBuilder(sb, commandInfo);

        OutputArgsBuilder.GetClass(sb, commandInfo);

        sb.CloseClass();
        sb.CloseNamespace(commandInfo.NamespaceName);

        outputStrings.Add((hintName: commandInfo.Name, code: sb.ToString()));
        foreach (var subCommand in commandInfo.SubCommands)
        {
            GetSourcePartialArgs(subCommand, outputStrings);
        }
    }

    private static void FileOpening(StringBuilderWrapper sb)
    {
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;",
                       "using DragonFruit2.Validators;",
                       "using System.CommandLine;",
                       "using System.Diagnostics.CodeAnalysis;"]);
    }

    internal static void OpenClass(CommandInfo commandInfo, StringBuilderWrapper sb)
    {
        sb.AppendLines([
                "/// <summary>",
                $"""/// Auto-generated partial class for building CLI commands for <see cref="{commandInfo.Name}" />""",
                $"""/// and creating a new {commandInfo.Name} instance from a <see cref="System.CommandLine.ParseResult" />.""",
                "/// </summary>",
                $"public partial class {commandInfo.Name} : Args<{commandInfo.Name}>, IArgs<{commandInfo.Name}>"]);
        sb.OpenCurly();
    }

    internal static void FieldsAndProperties(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        foreach (var prop in commandInfo.Options.Concat(commandInfo.Arguments))
        {
            if (prop.Validators is not null && prop.Validators.Any())
            { sb.AppendLine($"""private List<Validator<{prop.TypeName}>>? {OutputHelpers.GetLocalSymbolName(prop.Name)}Validators;"""); }
        }
    }

    private static void Constructors(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        // TODO: Only generate the following constructor if the user does not create it
        sb.OpenMethod($"internal {commandInfo.Name}()");
        sb.CloseMethod();

        sb.AppendLine("[SetsRequiredMembers()]");
        var parameters = commandInfo.PropInfos
                         .Select(p => $"DataValue<{p.TypeName}> {p.Name.ToCamelCase()}DataValue");
        sb.OpenMethod($"private {commandInfo.Name}({string.Join(", ", parameters)})", "this()");

        foreach (var propInfo in commandInfo.PropInfos)
        {
            sb.AppendLine($"""if ({propInfo.Name.ToCamelCase()}DataValue.IsSet) {propInfo.Name} = {propInfo.Name.ToCamelCase()}DataValue.Value;""");
        }

        sb.CloseMethod();
    }

    internal static void ValidateMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod("public override IEnumerable<ValidationFailure> Validate()");
        sb.AppendLine("var failures = new List<ValidationFailure>();");
        sb.AppendLine("InitializeValidators();");
        sb.AppendLine();
        foreach (var prop in commandInfo.PropInfos)
        {
            if (prop.Validators is not null && prop.Validators.Any())
            {
                var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
                sb.OpenIf($"{localSymbolName}Validators is not null");
                sb.OpenForEach($"var validator in {localSymbolName}Validators");
                sb.AppendLine($"""failures.AddRange(validator.Validate({prop.Name}));""");
                sb.CloseForEach();
                sb.CloseIf();
            }
        }
        sb.AppendLine();
        sb.AppendLine("return failures;");
        sb.CloseMethod();
    }

    internal static void InitializeValidatorsMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod($"""private void InitializeValidators()""");
        foreach (var prop in commandInfo.PropInfos)
        {
            if (prop.Validators is not null && prop.Validators.Any())
            {
                var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
                sb.AppendLine($"{localSymbolName}Validators ??= new List<Validator<{prop.TypeName}>>();");
                foreach (var validator in prop.Validators)
                {
                    sb.Append($"""{localSymbolName}Validators.Add(new {validator.Name}Validator<{prop.TypeName}>("{prop.Name}", """);
                    sb.Append(string.Join(", ", validator.ConstructorArguments));
                    if (validator.NamedArguments.Any())
                    {
                        sb.Append(",");
                        sb.Append(string.Join(", ", validator.NamedArguments.Select(kv => $"{kv.Key}: {kv.Value}")));
                    }
                    sb.AppendLine("));");
                }
                sb.AppendLine();
            }
        }
        sb.CloseMethod();
    }

    internal static void GetArgsBuilder(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod($"public static ArgsBuilder<{commandInfo.Name}> GetArgsBuilder(Builder<{commandInfo.Name}> builder)");
        sb.AppendLine($"return new {commandInfo.Name}.{commandInfo.Name}ArgsBuilder();");
        sb.CloseMethod();
    }


}
