using DragonFruit2.GeneratorSupport;

namespace DragonFruit2.Generators;

internal class OutputPartialArgs
{
    internal static string GetSourcePartialArgs(CommandInfo commandInfo)
    {
        var sb = new StringBuilderWrapper();
        FileOpening(sb);
        sb.OpenNamespace(commandInfo.NamespaceName);

        OpenClass(commandInfo, sb);

        FieldsAndProperties(sb, commandInfo);
        sb.AppendLine();
        Constructors(sb, commandInfo);
        ValidateMethod(sb, commandInfo);
        InitializeValidatorsMethod(sb, commandInfo);
        RegisterCustomDefaultsPartialMethod(sb, commandInfo);
        GetArgsBuilder(sb, commandInfo);

        OutputArgsBuilder.GetClass(sb, commandInfo);

        sb.CloseClass();
        sb.CloseNamespace(commandInfo.NamespaceName);

        return sb.ToString();
    }

    private static void FileOpening(StringBuilderWrapper sb)
    {
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;",
                       "using DragonFruit2.Validators;",
                       "using System.CommandLine;",
                       "using System.Diagnostics.CodeAnalysis;"]);
    }

    internal static void OpenClass(CommandInfo commandInfo, StringBuilderWrapper sb)
    {
        var baseType = commandInfo.BaseName ?? $"IArgs<{commandInfo.Name}>";
        sb.XmlSummary(
                $"""Auto-generated partial class for building CLI commands for <see cref="{commandInfo.Name}"/>" and creating a new {commandInfo.Name} instance from a <see cref="System.CommandLine.ParseResult" />.""");
        sb.OpenClass($"{commandInfo.ArgsAccessibility} partial class {commandInfo.Name} : {baseType}");
    }

    internal static void FieldsAndProperties(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        foreach (var prop in commandInfo.Options.Concat(commandInfo.Arguments))
        {
            if (prop.Validators is not null && prop.Validators.Any())
            { sb.AppendLine($"""private List<Validator<{prop.TypeName}>>? {OutputHelpers.GetLocalSymbolName(prop.Name)}Validators;"""); }
        }
    }

    private static void Constructors(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        // TODO: Can we allow both base setting of properties and respect for a user-created parameterles ctor? Maybe not.
        // TODO: Only generate the following constructor if the user does not create it
        if (commandInfo.PropInfos.Any())
        {
            sb.OpenMethod($"public {commandInfo.Name}()");
            sb.CloseMethod();
        }

        sb.Append("[SetsRequiredMembers()]");
        var parameters = string.Join(", ", commandInfo.SelfAndAncestorPropInfos
                         .Select(CtorParameter));
        var calledCtor = commandInfo.AncestorPropInfos.Any()
            ? $"base({string.Join(", ", commandInfo.AncestorPropInfos
                        .Select(p => $"{p.Name.ToCamelCase()}DataValue"))})"
            : commandInfo.PropInfos.Any()
                ? "this()"
                : null;
        sb.OpenConstructor($"protected {commandInfo.Name}({string.Join(", ", parameters)})", calledCtor);

        foreach (var propInfo in commandInfo.PropInfos)
        {

            string dataValueName = $"{propInfo.Name.ToCamelCase()}DataValue";
            sb.AppendLine($"""if (ValueIsAvailable({dataValueName})) {propInfo.Name} = {dataValueName}.Value;""");
        }

        sb.OpenMethod("static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)");
        sb.AppendLine("return dataValue switch");
        sb.OpenCurly();
        sb.AppendLine("null => false,");
        sb.AppendLine("{ IsSet: true } => true,");
        sb.AppendLine("_ => false");
        sb.CloseCurly(endStatement: true);
        sb.CloseMethod();

        sb.CloseConstructor();

        static string CtorParameter(PropInfo p)
            => $"DataValue<{p.TypeName}>? {p.Name.ToCamelCase()}DataValue";
    }

    internal static void ValidateMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod("public IEnumerable<ValidationFailure> Validate()");
        sb.AppendLine("var failures = new List<ValidationFailure>();");
        sb.AppendLine("InitializeValidators();");
        sb.AppendLine();
        foreach (var prop in commandInfo.PropInfos)
        {
            if (prop.Validators is not null && prop.Validators.Any())
            {
                var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
                sb.OpenIf($"{localSymbolName}Validators is not null");
                sb.OpenForEach($"var validator in {localSymbolName}Validators");
                sb.AppendLine($"""failures.AddRange(validator.Validate({prop.Name}));""");
                sb.CloseForEach();
                sb.CloseIf();
            }
        }
        sb.AppendLine();
        sb.AppendLine("return failures;");
        sb.CloseMethod();
    }

    internal static void InitializeValidatorsMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod($"""private void InitializeValidators()""");
        foreach (var prop in commandInfo.PropInfos)
        {
            if (prop.Validators is not null && prop.Validators.Any())
            {
                var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
                sb.AppendLine($"{localSymbolName}Validators ??= new List<Validator<{prop.TypeName}>>();");
                foreach (var validator in prop.Validators)
                {
                    sb.Append($"""{localSymbolName}Validators.Add(new {validator.Name}Validator<{prop.TypeName}>("{prop.Name}", """);
                    sb.Append(string.Join(", ", validator.ConstructorArguments));
                    if (validator.NamedArguments.Any())
                    {
                        sb.Append(",");
                        sb.Append(string.Join(", ", validator.NamedArguments.Select(kv => $"{kv.Key}: {kv.Value}")));
                    }
                    sb.AppendLine("));");
                }
                sb.AppendLine();
            }
        }
        sb.CloseMethod();
    }

    internal static void RegisterCustomDefaultsPartialMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.AppendLine();
        sb.Append($"static partial void RegisterCustomDefaults(Builder<{commandInfo.RootName}> builder, DefaultDataProvider<{commandInfo.RootName}> defaultDataProvider);");
        sb.AppendLine();
    }


    internal static void GetArgsBuilder(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod($"public static ArgsBuilder<{commandInfo.RootName}> GetArgsBuilder(Builder<{commandInfo.RootName}> builder)");
        sb.AppendLine($"return new {commandInfo.Name}.{commandInfo.Name}ArgsBuilder();");
        sb.CloseMethod();
    }
}
